const error: { [key: string]: string } = {
  'network error': 'Network error: Failed to connect to the server.',
  notAuthorized: 'Not authorized: You are not authorized to access this page.',
  userExists: 'User already exists.',
  getTeamLeaders: 'Failed to get team leaders.',
  getCountries: 'Failed to get countries.',
  getRecruiter: 'Failed to get recruiter.',
  getInterestSkills: 'Failed to get interest skills.',
  removeUser: 'Failed to remove user.',
  removeTeamLeader: 'Failed to remove team leader or team leader in use.',
  removeCompany: 'Failed to remove company.',
  removeCandidate: 'Failed to remove candidate.',
  removeInterestSkills: 'Failed to remove interest skills.',
  removeJobs: 'Failed to remove job.',
  removeTestimonials: 'Failed to remove testimonial.',
  getJobs: 'Failed to get jobs.',
  getCandidates: 'Failed to get candidates.',
  talentPoolInterestExists: 'Talent pool interest already exists.',
  acceptTerms: 'You need agree to privacy policy to continue.',
  registerModalCompany: 'Failed to register company.',
  tokenTalentPool: 'Failed to verify token.',
  getTestimonials: 'Failed to get testimonials.',
  contactSuccess: 'Failed to send contact.',
  addTeamLeaderCandidate: 'Failed to add team leader in candidate.',
  registerCandidate: 'Failed to register candidate.',
  candidateExists: 'Candidate already exists.',
  policyTerms: 'You need agree to terms and conditions to continue.',
  registerCompany: 'Failed to register company.',
  passwordNotConfirmed: 'Password not confirmed.',
  incorrectPassword: 'Incorrect password.',
  passwordMinCharacters: 'Password must be at least 6 characters.',
  candidateHasRelations: 'You cannot exclude a candidate who is related.',
  companieExists: 'Company already exists.',
  addRecruiterCandidate: 'Failed to add recruiter in candidate.',
  tokenBusinessAccept: 'Failed to accepted business.',
  applyNow: 'Failed to apply now job',
};

export default function errorString(key: string): string {
  return error[key] || '';
}
